
import { z } from "zod";

export const articleFormSchema = z.object({
  title: z.string().min(1, "Title is required"),
  title_fr: z.string().optional(),
  slug: z.string().min(1, "Slug is required"),
  slug_fr: z.string().optional(),
  excerpt: z.string().optional(),
  excerpt_fr: z.string().optional(),
  content: z.string().optional(),
  content_fr: z.string().optional(),
  author_id: z.string().optional(),
  category_id: z.string().optional(),
  published: z.boolean().default(false),
  featured: z.boolean().default(false),
  pin_as_hero: z.boolean().default(false),
  exclusive: z.boolean().default(false),
  featured_image_url: z.string().optional(),
  meta_title: z.string().optional(),
  meta_title_fr: z.string().optional(),
  meta_description: z.string().optional(),
  meta_description_fr: z.string().optional(),
  meta_keywords: z.string().optional(),
  meta_keywords_fr: z.string().optional(),
  og_image_url: z.string().optional(),
  canonical_url: z.string().optional(),
  canonical_url_fr: z.string().optional(),
  instagram_enabled: z.boolean().default(false),
  twitter_enabled: z.boolean().default(false),
  linkedin_enabled: z.boolean().default(false),
  instagram_caption: z.string().optional(),
  twitter_caption: z.string().optional(),
  linkedin_caption: z.string().optional(),
  social_hashtags: z.string().optional(),
  instagram_image_text: z.string().optional(),
  instagram_text_color: z.enum(['white', 'black']).default('white'),
  twitter_image_text: z.string().optional(),
  twitter_text_color: z.enum(['white', 'black']).default('white'),
  linkedin_image_text: z.string().optional(),
  linkedin_text_color: z.enum(['white', 'black']).default('white'),
});

export type ArticleFormData = z.infer<typeof articleFormSchema>;
