// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ecmhvuvlzelqddjetgts.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVjbWh2dXZsemVscWRkamV0Z3RzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5ODQ4MTcsImV4cCI6MjA2NDU2MDgxN30.ALRd0JQfFgwEeuMwY-Jbdi_xsWpCk4J1BjBRSh_TQHQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);